version: '3.8'
services:
  order-service:
    build: OrderService
    ports:
      - "8082:8082"
    restart: always
    environment:
      - API_CATALOG_BASEURL=http://product-service:8083
  product-service:
    build: ProductService
    ports:
      - "8083:8083"
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/producttest
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
  postgres-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=producttest