server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/producttest
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect