server.port: 8082
api:
  catalog:
    baseUrl: "http://localhost:8083"
resilience4j:
  circuitbreaker:
    instances:
      order:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  ratelimiter:
    instances:
      rateLimiterApi:
        register-health-indicator: true
        limit-for-period: 5
        limit-refresh-period: 60s
        timeout-duration: 0s
        allow-health-indicator-to-fail: true
        event-consumer-buffer-size: 50
---
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers.enabled: true
    ratelimiters:
      enabled: true
